
`%nin%` <- function(x, y) {
  !x %in% y
}

#' Read benchmark output generated by nanobench,
#' 
#' This function expects the output in the style written for Linux machines,
#' which includes columns not collected on macOS.
#'
#' @param filename 
#'
#' @return a tibble
#' @export
#'
read_benchmark <- function(filename)
{
  d <- read.so::read_md(filename)
  # Keep only the interesting columns
  d <- d[,c(1,3,4,7,10)]
  names(d) <- c("t","err","ins","branches", "name")
  d$err <- as.numeric(sub("%","",d$err))/100
  mutate(d,
         ins = as.integer(ins),
         branches = as.integer(branches),
         name = gsub("`","",name, fixed=TRUE),
         name = factor(name))
}

#' Read VTune data from my summary file
#' 
#' In the resulting tibble, the column 'type' indicates what kind of measurement
#' is carried in the 't' column for that row.
#'     full: t is the time in seconds taken by this function in the full program
#'
#' @param filename 
#'
#' @return a tibble
#' @export
#'
read_vtune <- function(filename)
{
  d <- read_csv(filename, col_types="ifdf")
  pivot_wider(d, names_from=func, values_from=t)  
}

#' Read VTune hotspot reports
#'
#' @param filename 
#'
#' @return a hotspot tibble
#' @export
#'
#' @examples
read_vtune_hotspots <- function(filename)
{
  checkmate::assert_file(filename)
  readr::read_tsv(filename, show_col_types=FALSE) |>
    rename(func = Function,
           t = `CPU Time`,
           teff = `CPU Time:Effective Time`,
           tspin = `CPU Time:Spin Time`,
           tspinimb = `CPU Time:Spin Time:Imbalance or Serial Spinning`,
           tspinlock = `CPU Time:Spin Time:Lock Contention`,
           tspinother = `CPU Time:Spin Time:Other`,
           tover = `CPU Time:Overhead Time`,
           tovercreate = `CPU Time:Overhead Time:Creation`,
           toversched = `CPU Time:Overhead Time:Scheduling`,
           toverred = `CPU Time:Overhead Time:Reduction`,
           toveratom = `CPU Time:Overhead Time:Atomics`,
           toverother = `CPU Time:Overhead Time:Other`,
           lib = Module,
           funcname = `Function (Full)`,
           file = `Source File`,
           addr = `Start Address`)
}
